//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.6
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from F:\C#\Misaka12456 (Misaka Castle)\Rabotora\Rabotora.Core\Rsf\RabotoraScriptFormat.g4 by ANTLR 4.6.6

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Rabotora.Core.Rsf {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IRabotoraScriptFormatListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.6")]
public partial class RabotoraScriptFormatBaseListener : IRabotoraScriptFormatListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="RabotoraScriptFormatParser.funcWord"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncWord([NotNull] RabotoraScriptFormatParser.FuncWordContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RabotoraScriptFormatParser.funcWord"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncWord([NotNull] RabotoraScriptFormatParser.FuncWordContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="RabotoraScriptFormatParser.plainString"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPlainString([NotNull] RabotoraScriptFormatParser.PlainStringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RabotoraScriptFormatParser.plainString"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPlainString([NotNull] RabotoraScriptFormatParser.PlainStringContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="RabotoraScriptFormatParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValue([NotNull] RabotoraScriptFormatParser.ValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RabotoraScriptFormatParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValue([NotNull] RabotoraScriptFormatParser.ValueContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="RabotoraScriptFormatParser.values"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValues([NotNull] RabotoraScriptFormatParser.ValuesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RabotoraScriptFormatParser.values"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValues([NotNull] RabotoraScriptFormatParser.ValuesContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="RabotoraScriptFormatParser.cmd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCmd([NotNull] RabotoraScriptFormatParser.CmdContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RabotoraScriptFormatParser.cmd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCmd([NotNull] RabotoraScriptFormatParser.CmdContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="RabotoraScriptFormatParser.segment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSegment([NotNull] RabotoraScriptFormatParser.SegmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RabotoraScriptFormatParser.segment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSegment([NotNull] RabotoraScriptFormatParser.SegmentContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="RabotoraScriptFormatParser.segmentBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSegmentBody([NotNull] RabotoraScriptFormatParser.SegmentBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RabotoraScriptFormatParser.segmentBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSegmentBody([NotNull] RabotoraScriptFormatParser.SegmentBodyContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="RabotoraScriptFormatParser.typeDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeDef([NotNull] RabotoraScriptFormatParser.TypeDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RabotoraScriptFormatParser.typeDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeDef([NotNull] RabotoraScriptFormatParser.TypeDefContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="RabotoraScriptFormatParser.typeDefs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeDefs([NotNull] RabotoraScriptFormatParser.TypeDefsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RabotoraScriptFormatParser.typeDefs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeDefs([NotNull] RabotoraScriptFormatParser.TypeDefsContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="RabotoraScriptFormatParser.classDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassDef([NotNull] RabotoraScriptFormatParser.ClassDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RabotoraScriptFormatParser.classDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassDef([NotNull] RabotoraScriptFormatParser.ClassDefContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="RabotoraScriptFormatParser.funcDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncDef([NotNull] RabotoraScriptFormatParser.FuncDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RabotoraScriptFormatParser.funcDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncDef([NotNull] RabotoraScriptFormatParser.FuncDefContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="RabotoraScriptFormatParser.classSegment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassSegment([NotNull] RabotoraScriptFormatParser.ClassSegmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RabotoraScriptFormatParser.classSegment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassSegment([NotNull] RabotoraScriptFormatParser.ClassSegmentContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="RabotoraScriptFormatParser.funcSegment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncSegment([NotNull] RabotoraScriptFormatParser.FuncSegmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RabotoraScriptFormatParser.funcSegment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncSegment([NotNull] RabotoraScriptFormatParser.FuncSegmentContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="RabotoraScriptFormatParser.body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBody([NotNull] RabotoraScriptFormatParser.BodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RabotoraScriptFormatParser.body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBody([NotNull] RabotoraScriptFormatParser.BodyContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="RabotoraScriptFormatParser.script"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScript([NotNull] RabotoraScriptFormatParser.ScriptContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RabotoraScriptFormatParser.script"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScript([NotNull] RabotoraScriptFormatParser.ScriptContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace Rabotora.Core.Rsf
