<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWindowsForms>true</UseWindowsForms>
        <ImplicitUsings>enable</ImplicitUsings>
        <CharacterSet>Unicode</CharacterSet>
        <AssemblyName>Game</AssemblyName>
        <RootNamespace>Rabotora.Launcher</RootNamespace>
        <AssemblyTitle>Rabotora Visual Novel Engine Launcher</AssemblyTitle>
        <Company>Misaka Castle, Rabotora Tower Project and all Rabotora contributors</Company>
        <Copyright>(C)Copyright 2021-2025 Rabotora Tower Project</Copyright>
        <Version>0.0.1-alpha</Version>
        <Authors>Rabotora Tower Project</Authors>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="SkiaSharp" Version="3.116.1" />
      <PackageReference Include="Vortice.D3DCompiler" Version="3.6.2" />
      <PackageReference Include="Vortice.Direct2D1" Version="3.6.2" />
      <PackageReference Include="Vortice.Direct3D11" Version="3.6.2" />
      <PackageReference Include="Vortice.Win32" Version="2.2.7" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\RabotoraEngine\RabotoraEngine.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Update="Data\Unpacked\Sprites\splash_ageWarning.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Data\Unpacked\Sprites\splash_devLogo.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>