<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AssemblyName>RabotoraXSampleGame</AssemblyName>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyTitle>RabotoraX Windows Sample Test Project</AssemblyTitle>
        <Company>Misaka Castle Group and RabotoraX Contributors</Company>
        <Copyright>(C) Misaka Castle Group and RabotoraX Contributors. All rights reserved. Licensed under 123 Open-Source Organization MIT Public License 2.0.</Copyright>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
        <PublishAot>true</PublishAot>
        <ImportWindowsDesktopTargets>false</ImportWindowsDesktopTargets>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\RabotoraX.Core\RabotoraX.Core.csproj" />
        <ProjectReference Include="..\RabotoraX.Interop.Direct3D11\RabotoraX.Interop.Direct3D11.csproj" />
        <ProjectReference Include="..\RabotoraX.Interop.Direct3D12\RabotoraX.Interop.Direct3D12.csproj" />
        <ProjectReference Include="..\RabotoraX.Interop.Win32\RabotoraX.Interop.Win32.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Remove="Resources\SneakySnitch.ogg" />
        <None Update="Resources\Demo2D_Data.pkg">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Resources\Demo3D_Data.pkg">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
