<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AssemblyName>RabotoraXSampleGame</AssemblyName>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <TieredCompilation>false</TieredCompilation>
        <AssemblyTitle>RabotoraX Windows Sample Test Project</AssemblyTitle>
        <Company>Misaka Castle Group and RabotoraX Contributors</Company>
        <Copyright>(C) Misaka Castle Group and RabotoraX Contributors. All rights reserved. Licensed under 123 Open-Source Organization MIT Public License 2.0.</Copyright>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\RabotoraX.Core\RabotoraX.Core.csproj" />
        <ProjectReference Include="..\RabotoraX.Interop.Direct3D11\RabotoraX.Interop.Direct3D11.csproj" />
        <ProjectReference Include="..\RabotoraX.Interop.Win32\RabotoraX.Interop.Win32.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Remove="Resources\SneakySnitch.ogg" />
        <EmbeddedResource Include="Resources\SneakySnitch.ogg" />
    </ItemGroup>

</Project>
