using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;

namespace RabotoraX.Analyzers;

[DiagnosticAnalyzer(LanguageNames.CSharp)]
public sealed class SerializationAttributeTargetAnalyzer : DiagnosticAnalyzer
{
	public const string DiagnosticId = "RAT0005";
	private const string TargetAttributeName = "RabotoraX.Core.Serialization.RSerializableFieldAttribute";
	
	private readonly static LocalizableString Title = "[RSerializableField] must decorate to the backing field of an auto-property";

	private readonly static LocalizableString MessageFormat = "The property '{0}' incorrectly uses [RSerializableField]. " +
	                                                          "Please replace '[RSerializableField]' with '[field: RSerializableField]' to apply the attribute to the property itself, " +
	                                                          "as the serialization framework (RBinaryFormatter) only recognizes attributes applied to a field.";
	
	private readonly static LocalizableString Description = "The deserialization framework (RBinaryFormatter) only recognizes fields to be serialized and deserialized. " +
	                                                          "Please use [field: RSerializableField] to apply the attribute to the backing field of an auto-property to include the property in serialization and deserialization, " +
	                                                          "or simply remove the [RSerializableField] attribute if you intend to not serialize this property.";
	private const string Category = "Usage";
	// set to Error serverity to overwrite the error generated by the compiler as CS0592 (Attribute is not valid on this declaration type. It is only valid on 'field' declarations)
	private readonly static DiagnosticDescriptor Rule = new(DiagnosticId, Title, MessageFormat, Category, DiagnosticSeverity.Error, isEnabledByDefault: true, description: Description);
	
	public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics => [Rule];
	
	public override void Initialize(AnalysisContext context)
	{
		context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.None);
		context.EnableConcurrentExecution();
		
		context.RegisterCompilationStartAction(ctxCompilation =>
		{
			var attributeSymbol = ctxCompilation.Compilation.GetTypeByMetadataName(TargetAttributeName);
			if (attributeSymbol == null) return;
			
			ctxCompilation.RegisterSyntaxNodeAction(ctxSyntax => AnalyzeProperty(ctxSyntax, attributeSymbol), SyntaxKind.PropertyDeclaration);
		});
	}

	[SuppressMessage("ReSharper", "ForeachCanBePartlyConvertedToQueryUsingAnotherGetEnumerator")]
	private static void AnalyzeProperty(SyntaxNodeAnalysisContext context, INamedTypeSymbol attributeSymbol)
	{
		var declProperty = (PropertyDeclarationSyntax)context.Node;

		// Skip static properties as they cannot be serialized and deserialized
		if (declProperty.Modifiers.Any(SyntaxKind.StaticKeyword)) return;

		foreach (var attributeList in declProperty.AttributeLists)
		{
			if (attributeList.Target?.Identifier.IsKind(SyntaxKind.FieldKeyword) == true) continue;

			foreach (var attr in attributeList.Attributes)
			{
				if (IsTargetAttribute(context, attr, attributeSymbol))
				{
					var diagnostic = Diagnostic.Create(Rule, attr.GetLocation(), declProperty.Identifier.Text);
					context.ReportDiagnostic(diagnostic);
				}
			}
		}
	}

	private static bool IsTargetAttribute(SyntaxNodeAnalysisContext context, AttributeSyntax attr, INamedTypeSymbol targetSymbol)
	{
		var symbolInfo = context.SemanticModel.GetSymbolInfo(attr);
		return SymbolEqualityComparer.Default.Equals(symbolInfo.Symbol?.ContainingType, targetSymbol);
	}
}